---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dummyproject
  namespace: dummyproject
spec:
  image: hagrid.lab.printf.org/bgog/dummyproject
  interval: 1m0s
  secretRef:
    name: container-registry-cred
