---
apiVersion: v1
kind: Namespace
metadata:
  name: dummyproject
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dummyproject-cert
  namespace: dummyproject
spec:
  secretName: dummyproject-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dummyproject.printf.org"
  dnsNames:
  - "dummyproject.printf.org"
  