# build-with-kaniko.yml

name: Build with kaniko

on:
  push:
    branches: [ main ]
    # branches: [ "*" ]
    # paths:
    #   - "app/**"
    #   - ".github/workflows/build-docker.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  build-to-localrepo:
    name: "Build and Push Image"
    runs-on: k8s-test-runner
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug # the kaniko image
    permissions:
      contents: read # read the repository
      packages: write # to push to GHCR, omit for other container registry. https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action

    steps:
      # - name: Look at files
      #   working-directory: ./app
      #   run: |
      #     echo "curdir: $PWD"
      #     echo "ctx: ${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"
      #     echo "$(ls -l)"
      #     echo "$(find .)"
      - uses: actions/checkout@v4.1.1
      - name: Build and Push Image to docker registry with kaniko
        working-directory: ./app
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "hagrid.lab.printf.org": {
                "auth": "$(echo -n "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" | base64 )"
              }
            }
          }
          EOF

          /kaniko/executor --dockerfile="Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination="hagrid.lab.printf.org/$DOCKER_IMAGE_NAME:$(echo ${GITHUB_SHA} | head  -c 7)" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 5

        env: 
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE_NAME: "bgog/dummyproject"

# --destination="hagrid.lab.printf.org/$DOCKER_IMAGE_NAME:$(echo ${GITHUB_SHA} | head  -c 7)" \
# --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \