name: Python Application CI

on:
  push:
    branches: [ "fred" ]
    paths:
      - "app/**"
      - ".github/workflows/build-docker.yml"
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    name: "Run Tests"
    runs-on: k8s-test-runner #ubuntu-latest
    container:
      image: ghcr.io/actions/actions-runner:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'arm64'
        
    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      working-directory: ./app
      run: |
        python -m pytest tests/
